name: Continuous Integrations Deep Store

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        env:
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install -g json-server
      - run: json-server --watch db.json &
      - run: npm install @vue/cli-service --save-dev
      - run: npm i vue-template-compiler --save-dev
      - run: npm run serve
      - run: npx netlify-cli deploy --dir=public --prod
